package corbaConversion;


/**
* corbaConversion/IConversionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* Monday, November 20, 2023 3:24:23 PM WAT
*/

public interface IConversionRemoteOperations 
{
  double conversionMontant (double montant);
} // interface IConversionRemoteOperations
